on:
  push:
    tags:
      - "**"
jobs:
  call-publish:
    uses: hafeoz/rust-build-release-workflow/.github/workflows/build-and-publish.yaml@master
    permissions:
      contents: write      # attest-build-provenance (read), action-gh-release (write)
      id-token: write      # attest-build-provenance
      attestations: write  # attest-build-provenance
    with:
      fail-if-unreproducible: true
      target-regex: '^([^-]+)-([^-]+)-linux(-(musl|gnu)[^-]*)?$'
      skip-target: 'armv5te-unknown-linux-musleabi,armv5te-unknown-linux-gnueabi,powerpc-unknown-linux-gnu' # fails to compile zvariant-5.2.0
      rust-toolchain: 'nightly'
      rust-flags: '-Z remap-cwd-prefix=.'
